pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker image...'
                 sh 'docker build -t my-app:latest application/'
            }
        }
        
        stage('Run Container') {
            steps {
                echo 'Running container...'
                sh 'docker run -d -p 8085:80 --name my-app-container my-app:latest || true'
            }
        }

        stage('Push to Docker Hub') {
    steps {
        sh 'docker tag my-app:latest santhosh3567/my-app:latest'
        sh 'docker push santhosh3567/my-app:latest'
    }
}
    }
}
